spring:
  application:
    name: CurrencyExchange
  cache:
    type: simple
  jpa:
    hibernate:
      ddl-auto: create-drop
exchange:
  nbp:
    base-url: "http://api.nbp.pl/api/exchangerates/rates/c"
